source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GesturePacker_Example', :exclusive => true do
  pod "GesturePacker", :path => "../"
end

target 'GesturePacker_Tests', :exclusive => true do
  pod "GesturePacker", :path => "../"

  pod 'FBSnapshotTestCase'
end
